/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void ctrlWin_draw1(PApplet appc, GWinData data) { //_CODE_:ctrlWindow:376121:
  appc.background(255);
} //_CODE_:ctrlWindow:376121:


public void speed1Changed(GSlider source, GEvent event) { //_CODE_:speed1:864711:
  particles[0].changeSpeed(int(speed1.getValueF()));
} //_CODE_:speed1:864711:


public void heading1Changed(GSlider source, GEvent event) { //_CODE_:heading1:825433:
  particles[0].changeHeading(int(heading1.getValueF()));
} //_CODE_:heading1:825433:


public void speed2Changed(GSlider source, GEvent event) { //_CODE_:speed2:685340:
  particles[1].changeSpeed(int(speed2.getValueF()));
} //_CODE_:speed2:685340:


public void heading2Changed(GSlider source, GEvent event) { //_CODE_:heading2:702591:
  particles[1].changeHeading(int(heading2.getValueF()));
} //_CODE_:heading2:702591:


public void playSimClicked(GButton source, GEvent event) { //_CODE_:playSim:340018:

  // play or pause the simulation
  paused = !paused;
  
  // change button appearance on GUI
  if(playSim.getText().equals("Play Simulation")) {
    playSim.setText("Pause Simulation");
    playSim.setLocalColorScheme(GCScheme.RED_SCHEME);
  }
  else {
    playSim.setText("Play Simulation");
    playSim.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  }
} //_CODE_:playSim:340018:

public void resetClicked(GButton source, GEvent event) { //_CODE_:resetSim:511997:

  // pause the sim (if not already paused)
  if(paused) {
  }
  else {
    paused = true;
    playSim.setText("Play Simulation");
    playSim.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  }
  
  particles[0].resetParticle1();
  particles[1].resetParticle2();
 
} //_CODE_:resetSim:511997:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.CYAN_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  ctrlWindow = GWindow.getWindow(this, "Control Window", 0, 0, 350, 275, JAVA2D);
  ctrlWindow.noLoop();
  ctrlWindow.setActionOnClose(G4P.KEEP_OPEN);
  ctrlWindow.addDrawHandler(this, "ctrlWin_draw1");
  label1 = new GLabel(ctrlWindow, 135, 35, 80, 20);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("Controls");
  label1.setOpaque(false);
  speed1 = new GSlider(ctrlWindow, 50, 75, 100, 40, 10.0);
  speed1.setLimits(5, 0, 10);
  speed1.setNumberFormat(G4P.INTEGER, 0);
  speed1.setOpaque(false);
  speed1.addEventHandler(this, "speed1Changed");
  heading1 = new GSlider(ctrlWindow, 51, 125, 100, 40, 10.0);
  heading1.setLimits(0, 0, 360);
  heading1.setNumberFormat(G4P.INTEGER, 0);
  heading1.setOpaque(false);
  heading1.addEventHandler(this, "heading1Changed");
  speed2 = new GSlider(ctrlWindow, 200, 75, 100, 40, 10.0);
  speed2.setLimits(5, 0, 10);
  speed2.setNumberFormat(G4P.INTEGER, 0);
  speed2.setOpaque(false);
  speed2.addEventHandler(this, "speed2Changed");
  heading2 = new GSlider(ctrlWindow, 200, 125, 100, 40, 10.0);
  heading2.setLimits(180, 0, 360);
  heading2.setNumberFormat(G4P.INTEGER, 0);
  heading2.setOpaque(false);
  heading2.addEventHandler(this, "heading2Changed");
  playSim = new GButton(ctrlWindow, 50, 185, 100, 40);
  playSim.setText("Play Simulation");
  playSim.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  playSim.addEventHandler(this, "playSimClicked");
  resetSim = new GButton(ctrlWindow, 200, 185, 100, 40);
  resetSim.setText("Reset Simulation");
  resetSim.addEventHandler(this, "resetClicked");
  label3 = new GLabel(ctrlWindow, 50, 65, 100, 20);
  label3.setText("Particle 1 Speed");
  label3.setOpaque(false);
  label4 = new GLabel(ctrlWindow, 50, 115, 110, 20);
  label4.setText("Particle 1 Heading");
  label4.setOpaque(false);
  label6 = new GLabel(ctrlWindow, 200, 65, 100, 20);
  label6.setText("Particle 2 Speed");
  label6.setOpaque(false);
  label7 = new GLabel(ctrlWindow, 200, 115, 110, 20);
  label7.setText("Particle 2 Heading");
  label7.setOpaque(false);
  ctrlWindow.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow ctrlWindow;
GLabel label1; 
GSlider speed1; 
GSlider heading1; 
GSlider speed2; 
GSlider heading2; 
GButton playSim; 
GButton resetSim; 
GLabel label3; 
GLabel label4; 
GLabel label6; 
GLabel label7; 
